server:
  port: 8765

spring:
  cloud:
    gateway:
      routes:
        - id: ServiceProducts
          uri: http://localhost:8081/
          predicates:
            - Path=/serviceProducts/**
        - id: ServiceCart
          uri: http://localhost:8082/
          predicates:
            - Path=/serviceCart/**
        - id: ServiceFeedback
          uri: http://localhost:8083/
          predicates:
            - Path=/serviceFeedback/**
  application:
    name: api-gateway